categories:
  - title: "Security"
    label: security
  - title: "Added"
    labels:
      - feature
      - enhancement
  - title: "Fixed"
    label: bug
  - title: "Dependency Updates"
    label: dependencies
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'
template: |
  ## Changed

  $CHANGES
