name: release management
on:
  push:
    branches: [master]

jobs:
  update-draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v5.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
